<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 *
 * @category  Amadeco
 * @package   Amadeco_SmileCustomEntityLayeredNavigation
 * @copyright Copyright (c) Amadeco (https://www.amadeco.fr) - Ilan Parmentier
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter */
/** @var \Amadeco\SmileCustomEntityLayeredNavigation\ViewModel\Layer\Filter $viewModel */
/** @var \Amadeco\SmileCustomEntityLayeredNavigation\Block\Navigation\FilterRenderer $block */

$filterItems = $filterItems ?? [];
$viewModel = $block->getData('entity_layer_view_model');
?>
<?php if (!empty($filterItems)): ?>
    <ol class="items filter-items">
        <?php foreach ($filterItems as $filterItem): ?>
            <li class="item filter-item">
                <?php if ($filterItem->getCount() > 0): ?>
                    <a
                        href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                        rel="nofollow"
                    ><?= /* @noEscape */ $filterItem->getLabel() ?><?php
                    if ($viewModel->shouldDisplayEntityCountOnLayer()): ?> <span
                            class="count">
                                <?= /* @noEscape */ $localeFormatter->formatNumber((int) $filterItem->getCount()) ?><span
                                class="filter-count-label"><?php
                                if ($filterItem->getCount() == 1): ?>
                                    <?= $escaper->escapeHtml(__('item')) ?><?php
                                else:
                                    ?><?= $escaper->escapeHtml(__('items')) ?><?php
                                endif;?></span></span>
                        <?php endif; ?></a>
                <?php else : ?>
                    <?= /* @noEscape */ $filterItem->getLabel() ?><?php
                    if ($viewModel->shouldDisplayEntityCountOnLayer()): ?> <span
                            class="count">
                                <?= /* @noEscape */ $localeFormatter->formatNumber((int) $filterItem->getCount()) ?><span
                                class="filter-count-label"><?php
                                if ($filterItem->getCount() == 1): ?>
                                    <?= $escaper->escapeHtml(__('item')) ?><?php
                                else:
                                    ?><?= $escaper->escapeHtml(__('items')) ?><?php
                                endif;?></span></span>
                    <?php endif; ?>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ol>
<?php endif ?>