<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 *
 * @category  Amadeco
 * @package   Amadeco_SmileCustomEntityLayeredNavigation
 * @copyright Copyright (c) Amadeco (https://www.amadeco.fr) - Ilan Parmentier
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

/**
 * Attribute set frontend view block
 * @var \Amadeco\SmileCustomEntity\Block\Set\View $block
 */
?>
<?php if ($block->isFilteredEntity() === false) : ?>
    <?= $block->getAdditionalHtml() ?>
<?php endif ?>

<div class="page-products">
    <?= $block->getEntityListHtml() ?>
</div>